# change the build directory to be within react's scope
project_structure:
  build: client/src/artifacts

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.5.0
  - smartcontractkit/chainlink-brownie-contracts@0.2.1

compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0"
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.1"

# automatically fetch contract sources from Etherscan
autofetch_sources: True
dotenv: .env

networks:
  default: development
  development:
    # cmd_settings:
    #   mnemonic: brownie
    #   default_balance: 100000000000000000000
    #   unlock: <ACCOUNT ADDRESS HERE> # optionally add saved brownie account to Ganache
    #   # (requires explicit transfer of eth to accounts[-1])

    update_interval: 60
    verify: False

  kovan:
    eth-usd-price-feed: "0x9326BFA02ADD2366b30bacB125260Af641031331"
    verify: False
    update_interval: 60

wallets:
  from_key:
    0: ${PRIVATE_KEY1}
    1: ${PRIVATE_KEY2}

# enable output of development artifacts to load with react
dev_deployment_artifacts: true
